server:
  port: 10000
  servlet:
    context-path:
  shutdown: graceful

spring:
  profiles:
    active: local, service

common:
  swagger-open: true

jwt-secret: 4rNYiAtKtdoMxdwW # JWT密钥

api-config:
  upload-path: /Users/ckh/Documents/tmp/lgl/