
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itchen-lgl?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root1234
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: My-HikariCP
      minimum-idle: 20
      maximum-pool-size: 80
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
  redis:
    host: localhost
    password: 123456
    port: 6379
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 20
        max-wait: 10000ms
    timeout: 10000ms
  cache:
    redis:
      cache-null-values: true
      time-to-live: 5m
      key-prefix: "cache:"
  jackson:
    serialization:
      write_dates_as_timestamps: true
    time-zone: GMT+8
    generator:
      write_bigdecimal_as_plain: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: vip.itchen.domain
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 健康监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,shutdown
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
