server:
  port: 10001
  servlet:
    context-path:
  shutdown: graceful

spring:
  profiles:
    active: prod, service

common:
  swagger-open: false

jwt-secret: FzgITfQc5iPLFGgr # JWT密钥

logging:
  file:
    path: /usr/local/share/applications/itchen-admin