server:
  port: 10000
  servlet:
    context-path:
  shutdown: graceful

spring:
  profiles:
    active: prod, service

common:
  swagger-open: false

jwt-secret: MJRGr1fj0rmSFHkS # JWT密钥

logging:
  file:
    path: /usr/local/share/applications/itchen-lgl-api

api-config:
  upload-path: /usr/local/share/applications/itchen-lgl-api/img/